import { Patient, getEmergencyStatus, calculatePriority } from '../types/patient';

export function generateSamplePatients(): Patient[] {
  const now = Date.now();
  const minute = 60 * 1000;

  const rawPatients: Array<{
    id: string;
    name: string;
    age: number;
    gender: 'Male' | 'Female' | 'Other';
    contact: string;
    symptoms: string;
    severityScore: number;
    minutesAgo: number;
    assignedDoctor: string;
    department: string;
    status: 'Waiting' | 'Treated';
  }> = [
    {
      id: 'P101',
      name: 'Eleanor Vance',
      age: 64,
      gender: 'Female',
      contact: '+1 (555) 234-8901',
      symptoms: 'Acute ST-elevation myocardial infarction, radiating jaw pain, diaphoresis',
      severityScore: 10,
      minutesAgo: 14,
      assignedDoctor: 'Dr. Marcus Vance (Cardiology)',
      department: 'Cardiology ER',
      status: 'Waiting',
    },
    {
      id: 'P102',
      name: 'David Chen',
      age: 32,
      gender: 'Male',
      contact: '+1 (555) 345-6712',
      symptoms: 'High-speed motor vehicle collision, suspected tension pneumothorax, hypotension',
      severityScore: 9,
      minutesAgo: 22,
      assignedDoctor: 'Dr. Sarah Lin (Trauma)',
      department: 'Trauma Bay 1',
      status: 'Waiting',
    },
    {
      id: 'P103',
      name: 'Robert Thornton',
      age: 58,
      gender: 'Male',
      contact: '+1 (555) 890-1234',
      symptoms: 'Acute ischemic stroke signs, right-sided hemiparesis, sudden dysphasia',
      severityScore: 8,
      minutesAgo: 35,
      assignedDoctor: 'Dr. Rebecca Stone (Neurology)',
      department: 'Neurology Acute',
      status: 'Waiting',
    },
    {
      id: 'P104',
      name: 'Elena Rostova',
      age: 41,
      gender: 'Female',
      contact: '+1 (555) 567-8901',
      symptoms: 'Severe lower quadrant abdominal pain, peritoneal signs, suspected appendicitis',
      severityScore: 6,
      minutesAgo: 48,
      assignedDoctor: 'Dr. James Thorne (General Surgery)',
      department: 'General ER',
      status: 'Waiting',
    },
    {
      id: 'P105',
      name: 'Lucas Morales',
      age: 26,
      gender: 'Male',
      contact: '+1 (555) 678-9012',
      symptoms: 'Closed distal radius fracture, intact neurovascular status, moderate pain',
      severityScore: 3,
      minutesAgo: 65,
      assignedDoctor: 'Dr. Amanda Blake (Orthopedics)',
      department: 'Orthopedics ER',
      status: 'Waiting',
    },
    {
      id: 'P106',
      name: 'Amina Al-Mansoor',
      age: 72,
      gender: 'Female',
      contact: '+1 (555) 789-0123',
      symptoms: 'Severe respiratory distress, oxygen saturation 79% on room air, sepsis criteria met',
      severityScore: 10,
      minutesAgo: 11,
      assignedDoctor: 'Dr. Michael Chen (Pulmonology)',
      department: 'Resuscitation Bay',
      status: 'Waiting',
    },
    {
      id: 'P107',
      name: 'George Callahan',
      age: 69,
      gender: 'Male',
      contact: '+1 (555) 901-2345',
      symptoms: 'Severe hematemesis, hemodynamic instability, active upper GI bleed',
      severityScore: 8,
      minutesAgo: 29,
      assignedDoctor: 'Dr. Patricia Hayes (Gastroenterology)',
      department: 'General ER',
      status: 'Waiting',
    },
    {
      id: 'P108',
      name: 'Sophia Martinez',
      age: 19,
      gender: 'Female',
      contact: '+1 (555) 012-3456',
      symptoms: 'Persistent high fever (39.8°C), nuchal rigidity, photophobia',
      severityScore: 5,
      minutesAgo: 52,
      assignedDoctor: 'Dr. Rebecca Stone (Neurology)',
      department: 'Isolation ER',
      status: 'Waiting',
    },
    {
      id: 'P109',
      name: 'Arthur Pendelton',
      age: 81,
      gender: 'Male',
      contact: '+1 (555) 123-4567',
      symptoms: 'Mild dehydration, chronic lumbar strain, stable vitals',
      severityScore: 2,
      minutesAgo: 70,
      assignedDoctor: 'Dr. Kevin Miller (Internal Med)',
      department: 'Fast Track ER',
      status: 'Waiting',
    },
    {
      id: 'P110',
      name: 'Clara Oswald',
      age: 29,
      gender: 'Female',
      contact: '+1 (555) 234-5678',
      symptoms: 'Severe acute asthma exacerbation, refractory to albuterol nebulization, peak flow < 40%',
      severityScore: 7,
      minutesAgo: 26,
      assignedDoctor: 'Dr. Michael Chen (Pulmonology)',
      department: 'Resuscitation Bay',
      status: 'Waiting',
    },
    {
      id: 'P111',
      name: 'Noah Bennett',
      age: 9,
      gender: 'Male',
      contact: '+1 (555) 345-6789',
      symptoms: 'High fever, acute stridor, barking cough, mild retractions',
      severityScore: 6,
      minutesAgo: 39,
      assignedDoctor: 'Dr. Lisa Monroe (Pediatrics)',
      department: 'Pediatric ER',
      status: 'Waiting',
    },
    {
      id: 'P112',
      name: 'Hannah Abbott',
      age: 23,
      gender: 'Female',
      contact: '+1 (555) 456-7890',
      symptoms: 'Anaphylaxis following wasp sting, facial angioedema, audible inspiratory stridor',
      severityScore: 9,
      minutesAgo: 17,
      assignedDoctor: 'Dr. Sarah Lin (Trauma)',
      department: 'Resuscitation Bay',
      status: 'Waiting',
    },
    {
      id: 'P113',
      name: 'Julian Ross',
      age: 45,
      gender: 'Male',
      contact: '+1 (555) 567-8902',
      symptoms: 'Superficial laceration on left forearm, controlled bleeding, neurovascularly intact',
      severityScore: 2,
      minutesAgo: 82,
      assignedDoctor: 'Dr. Amanda Blake (Orthopedics)',
      department: 'Fast Track ER',
      status: 'Waiting',
    },
    {
      id: 'P114',
      name: 'Miriam Becker',
      age: 52,
      gender: 'Female',
      contact: '+1 (555) 678-9013',
      symptoms: 'Diabetic ketoacidosis (DKA) presentation, blood glucose 480 mg/dL, moderate lethargy',
      severityScore: 6,
      minutesAgo: 44,
      assignedDoctor: 'Dr. Kevin Miller (Internal Med)',
      department: 'General ER',
      status: 'Waiting',
    },
    {
      id: 'P115',
      name: 'Victor Campbell',
      age: 63,
      gender: 'Male',
      contact: '+1 (555) 789-0124',
      symptoms: 'Severe hypertensive emergency, BP 220/125 mmHg, blurriness and severe occipital headache',
      severityScore: 7,
      minutesAgo: 31,
      assignedDoctor: 'Dr. Marcus Vance (Cardiology)',
      department: 'Cardiology ER',
      status: 'Waiting',
    },
    {
      id: 'P116',
      name: 'Chloe Gallagher',
      age: 34,
      gender: 'Female',
      contact: '+1 (555) 890-1235',
      symptoms: 'Mild sprain of lateral ankle ligament, ambulating with minimal limp',
      severityScore: 1,
      minutesAgo: 95,
      assignedDoctor: 'Dr. Amanda Blake (Orthopedics)',
      department: 'Fast Track ER',
      status: 'Waiting',
    },
    {
      id: 'P117',
      name: 'Tariq Sterling',
      age: 48,
      gender: 'Male',
      contact: '+1 (555) 901-2346',
      symptoms: 'Suspected acute pancreatitis, radiating epigastric pain, persistent vomiting',
      severityScore: 5,
      minutesAgo: 58,
      assignedDoctor: 'Dr. Patricia Hayes (Gastroenterology)',
      department: 'General ER',
      status: 'Waiting',
    },
    {
      id: 'P118',
      name: 'Zoe Katsaros',
      age: 38,
      gender: 'Female',
      contact: '+1 (555) 012-3457',
      symptoms: 'Blunt thoracic trauma from bicycle collision, multiple rib fractures, tachypnea',
      severityScore: 7,
      minutesAgo: 33,
      assignedDoctor: 'Dr. Sarah Lin (Trauma)',
      department: 'Trauma Bay 2',
      status: 'Waiting',
    },
    {
      id: 'P119',
      name: 'Felix Gomez',
      age: 50,
      gender: 'Male',
      contact: '+1 (555) 123-4568',
      symptoms: 'Mild allergic contact dermatitis, localized rash, stable airway',
      severityScore: 2,
      minutesAgo: 88,
      assignedDoctor: 'Dr. Kevin Miller (Internal Med)',
      department: 'Fast Track ER',
      status: 'Waiting',
    },
    {
      id: 'P120',
      name: 'Nadia Petrov',
      age: 27,
      gender: 'Female',
      contact: '+1 (555) 234-5679',
      symptoms: 'Moderate concussion after sports collision, intermittent nausea, GCS 15',
      severityScore: 4,
      minutesAgo: 60,
      assignedDoctor: 'Dr. Rebecca Stone (Neurology)',
      department: 'Neurology Acute',
      status: 'Waiting',
    },
    {
      id: 'P121',
      name: 'Owen Bradley',
      age: 77,
      gender: 'Male',
      contact: '+1 (555) 345-6790',
      symptoms: 'Chronic arthritis flare-up, requesting prescription review, normal vitals',
      severityScore: 1,
      minutesAgo: 110,
      assignedDoctor: 'Dr. Amanda Blake (Orthopedics)',
      department: 'Fast Track ER',
      status: 'Waiting',
    },
    {
      id: 'P122',
      name: 'Selena Gomez-Diaz',
      age: 31,
      gender: 'Female',
      contact: '+1 (555) 456-7891',
      symptoms: 'Ruptured ectopic pregnancy suspicion, acute pelvic guarding, tachycardia',
      severityScore: 8,
      minutesAgo: 25,
      assignedDoctor: 'Dr. James Thorne (General Surgery)',
      department: 'Trauma Bay 1',
      status: 'Waiting',
    },
    {
      id: 'P123',
      name: 'Darius Thorne',
      age: 43,
      gender: 'Male',
      contact: '+1 (555) 567-8903',
      symptoms: 'Renal colic with severe flank pain, microscopic hematuria, restless',
      severityScore: 5,
      minutesAgo: 45,
      assignedDoctor: 'Dr. Kevin Miller (Internal Med)',
      department: 'General ER',
      status: 'Waiting',
    },
    {
      id: 'P124',
      name: 'Isabella Fontaine',
      age: 22,
      gender: 'Female',
      contact: '+1 (555) 678-9014',
      symptoms: 'First-degree burn on palm from kitchen stove, minimal blistering',
      severityScore: 2,
      minutesAgo: 75,
      assignedDoctor: 'Dr. Sarah Lin (Trauma)',
      department: 'Fast Track ER',
      status: 'Waiting',
    },
    {
      id: 'P125',
      name: 'Harvey Dent-Walsh',
      age: 67,
      gender: 'Male',
      contact: '+1 (555) 789-0125',
      symptoms: 'Atrial fibrillation with rapid ventricular response (HR 145 bpm), dizziness',
      severityScore: 6,
      minutesAgo: 38,
      assignedDoctor: 'Dr. Marcus Vance (Cardiology)',
      department: 'Cardiology ER',
      status: 'Waiting',
    },
    {
      id: 'P126',
      name: 'Liam Gallagher-Kaye',
      age: 5,
      gender: 'Male',
      contact: '+1 (555) 890-1236',
      symptoms: 'Minor nasal foreign body (small plastic bead), comfortable, non-occlusive',
      severityScore: 2,
      minutesAgo: 85,
      assignedDoctor: 'Dr. Lisa Monroe (Pediatrics)',
      department: 'Pediatric ER',
      status: 'Waiting',
    },
  ];

  return rawPatients.map((p) => {
    const arrivalTime = now - p.minutesAgo * minute;
    const waitingTimeMinutes = p.minutesAgo;
    const emergencyStatus = getEmergencyStatus(p.severityScore);
    const priority = calculatePriority(p.severityScore, waitingTimeMinutes);

    return {
      id: p.id,
      name: p.name,
      age: p.age,
      gender: p.gender,
      contact: p.contact,
      symptoms: p.symptoms,
      severityScore: p.severityScore,
      arrivalTime,
      waitingTimeMinutes,
      emergencyStatus,
      priority,
      assignedDoctor: p.assignedDoctor,
      department: p.department,
      status: p.status,
      severityHistory: [],
    };
  });
}
